version: "3.8"

services:
  mysql:
    image: mysql
    container_name: cableoperator
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_USER: root

    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3